const MODULE_ID = "plutonium-italiano";
const MODULE_PATH = `modules/${MODULE_ID}`;

const UI_TRANS = {
	"Filter": "Filtro", "Reset": "Reimposta", "Import": "Importa",
	"Export": "Esporta", "Save": "Salva", "Cancel": "Annulla",
	"Delete": "Elimina", "Close": "Chiudi", "Apply": "Applica",
	"Remove": "Rimuovi", "Add": "Aggiungi", "Edit": "Modifica",
	"Update": "Aggiorna", "Reload": "Ricarica", "Run": "Esegui",
	"Move": "Sposta", "Load": "Carica", "New": "Nuovo",
	"Name": "Nome", "Type": "Tipo", "Source": "Sorgente",
	"Tags": "Tag", "Level": "Livello", "CR": "GS",
	"None": "Nessuno", "All": "Tutti", "Any": "Qualsiasi",
	"Yes": "Sì", "No": "No", "Clear": "Pulisci",
	"Search": "Cerca", "Settings": "Impostazioni",
	"Configure": "Configura", "Configuration": "Configurazione",
	"Select": "Seleziona", "Select All": "Seleziona Tutto",
	"Deselect All": "Deseleziona Tutto", "Invert Selection": "Inverti Selezione",

	"Feeling Lucky?": "Mi Senti Fortunato?",
	"Find items...": "Cerca oggetti...",
	"Find spells...": "Cerca incantesimi...",
	"Find packages...": "Cerca pacchetti...",
	"Find compendium...": "Cerca compendi...",

	"Settings": "Impostazioni",
	"Importing": "Importazione",
	"Import Complete": "Importazione Completata",
	"Loading data...": "Caricamento dati...",
	"Loading...": "Caricamento...",
	"No results found.": "Nessun risultato trovato.",
	"Please wait...": "Attendere prego...",
	"Are you sure?": "Sei sicuro?",

	"Choose Importer": "Scegli Importatore",
	"Content Blocklist": "Blocco Contenuti",
	"Source Selection": "Selezione Fonti",
	"Data Sources": "Fonti Dati",
	"World Data Source Selector": "Selettore Fonti Mondo",
	"World Content Blocklist": "Blocco Contenuti Mondo",

	"Bestiary": "Bestiario", "Spells": "Incantesimi",
	"Items": "Oggetti", "Races": "Razze", "Classes": "Classi",
	"Backgrounds": "Background", "Feats": "Talenti",
	"Actions": "Azioni", "Creatures": "Creature",
	"Languages": "Lingue", "Tables": "Tabelle",
	"Vehicles": "Veicoli", "Objects": "Oggetti",
	"Psionics": "Psioniche", "Deities": "Divinità",
	"Optional Features": "Opzioni",
	"Variant Rules": "Regole Varianti",
	"Conditions/Diseases": "Condizioni/Malattie",
	"Cults/Boons": "Culti/Benefici",
	"Rewards": "Ricompense", "Recipes": "Ricette",
	"Traps/Hazards": "Trappole/Pericoli",
	"Decks": "Mazzi", "Maps": "Mappe",
	"Character Options": "Opzioni Personaggio",
	"Text": "Testo", "UI": "Interfaccia",

	// Config sezioni
	"Config Editor": "Editor Configurazione",
	"Preferences": "Preferenze",
	"Appearance": "Aspetto",
	"Markdown": "Markdown",
	"Tokens": "Token",
	"Actors": "Attori",
	"Other Options": "Altre Opzioni",
	"Help": "Aiuto",
	"Always Save": "Salva Sempre",
	"Save and Close": "Salva e Chiudi",
	"Discard and Close": "Annulla e Chiudi",
	"Discard": "Annulla",
	"Confirm": "Conferma",
	"Continue": "Continua",

	// Sezioni Import
	"Import (Creatures)": "Importa (Creature)",
	"Import (Creature Features)": "Importa (Feature Creature)",
	"Import (Vehicles)": "Importa (Veicoli)",
	"Import (Vehicle Upgrades)": "Importa (Potenziamenti Veicoli)",
	"Import (Objects)": "Importa (Oggetti)",
	"Import (Object Features)": "Importa (Feature Oggetti)",
	"Import (Feats)": "Importa (Talenti)",
	"Import (Backgrounds)": "Importa (Background)",
	"Import (Background Features)": "Importa (Feature Background)",
	"Import (Classes & Subclasses)": "Importa (Classi & Sottoclassi)",
	"Import (Class & Sub. Features)": "Importa (Feature Classi & Sottocl.)",
	"Import (Items)": "Importa (Oggetti)",
	"Import (Psionics)": "Importa (Psioniche)",
	"Import (Species)": "Importa (Razze)",
	"Import (Species Features)": "Importa (Feature Razze)",
	"Import (Table)": "Importa (Tabella)",
	"Import (Spells)": "Importa (Incantesimi)",
	"Import (Rules)": "Importa (Regole)",
	"Import (Languages)": "Importa (Lingue)",
	"Import (Options & Features)": "Importa (Opzioni & Feature)",
	"Import (Conditions & Diseases)": "Importa (Condizioni & Malattie)",
	"Import (Cults & Supernatural Boons)": "Importa (Culti & Benefici)",
	"Import (Actions)": "Importa (Azioni)",
	"Import (Gifts & Rewards)": "Importa (Doni & Ricompense)",
	"Import (Char. Creation Options)": "Importa (Opzioni Creazione)",
	"Import (Deities)": "Importa (Divinità)",
	"Import (Recipes)": "Importa (Ricette)",
	"Import (Traps)": "Importa (Trappole)",
	"Import (Trap Features)": "Importa (Feature Trappole)",
	"Import (Hazards)": "Importa (Pericoli)",
	"Import (Adventures)": "Importa (Avventure)",
	"Import (Books)": "Importa (Libri)",
	"Import (Maps)": "Importa (Mappe)",
	"Import (Decks)": "Importa (Mazzi)",
	"Import (Facilities)": "Importa (Strutture)",

	// Tool window titles
	"Package Importer": "Importa Pacchetti",
	"Directory Cleaner": "Pulisci Directory",
	"Bulk Directory Mover": "Sposta Directory",
	"Bulk Ownership Editor": "Editor Proprietà",
	"Bulk Prototype Token Editor": "Editor Token Prototipo",
	"Directory Deduplicator": "Dedup Directory",
	"Compendium Ownership Updater": "Aggiorna Proprietà Compendio",
	"Loot Generator": "Generatore Bottino",
	"Item Cleaner": "Pulisci Oggetti",
	"Spell Prepared Toggler": "Attiva/Disattiva Incantesimi",
	"Row Cleaner": "Pulisci Righe",
	"Art Browser": "Browser Arte",
	"Changelog": "Novità",
	"Report a Bug": "Segnala Bug",

	// Dialog titles
	"File Type Mismatch": "Tipo File Non Corrispondente",
	"Enter Proficiency Bonus": "Inserisci Bonus Competenza",
	"Enter Spell Level": "Inserisci Livello Incantesimo",
	"Enter Class Level": "Inserisci Livello Classe",
	"Filter Combination Logic": "Logica Combinazione Filtri",
	"Unsaved Changes": "Modifiche Non Salvate",
	"Reset Blocklist": "Reimposta Blocco",
	"Exclude All": "Escludi Tutto",
	"Save to File": "Salva su File",
	"Load from File": "Carica da File",
	"Select Snapshot Deck": "Seleziona Mazzo Istantanea",
	"Select Snapshot": "Seleziona Istantanea",
	"Duplicate Snapshot": "Duplica Istantanea",
	"Snapshot Name": "Nome Istantanea",
	"Snapshot Deck Name": "Nome Mazzo Istantanea",
	"Delete Snapshot Decks": "Elimina Mazzi Istantanea",
	"Delete Snapshots": "Elimina Istantanee",
	"Too Many Sources": "Troppe Fonti",
	"Enter Gold Amount": "Inserisci Quantità Oro",
	"Reset Item Filters": "Reimposta Filtri Oggetti",
	"Customize Import": "Personalizza Import",
	"Updated Not Configured": "Aggiornato Non Configurato",
	"Token Name": "Nome Token",
	"Select Token Size": "Seleziona Dimensione Token",
	"Image URL": "URL Immagine",
	"Edit Folder Path": "Modifica Percorso Cartella",
	"Select Version...": "Seleziona Versione...",
	"Select Existing Item...": "Seleziona Oggetto Esistente...",

	// Config settings names (più visibili)
	"Streamer Mode": "Modalità Streamer",
	"Compact Header Buttons": "Bottoni Compatti Header",
	"Compact Directory Buttons": "Bottoni Compatti Directory",
	"Compact Chat": "Chat Compatta",
	"Compact Scenes Directory": "Directory Scene Compatta",
	"Compact Actors Directory": "Directory Attori Compatta",
	"Compact Items Directory": "Directory Oggetti Compatta",
	"Compact Journal Entries": "Note Diario Compatte",
	"Compact Rollable Tables": "Tabelle Rollabili Compatte",
	"Compact Card Stacks": "Mazzi di Carte Compatti",
	"Compact Compendium Packs": "Pacchetti Compendio Compatti",
	"Compact Macros": "Macro Compatte",
	"Hide Directory Buttons": "Nascondi Bottoni Directory",
	"Hide Sheet Menu Button": "Nascondi Bottone Menu Scheda",
	"Hide Update Notifications": "Nascondi Notifiche Aggiornamento",
	"Fast Animations": "Animazioni Veloci",
	"Fast Tooltips": "Tooltip Veloci",
	"Enable Custom Tooltips": "Abilita Tooltip Personalizzati",
	"Display Detected Backend": "Mostra Backend Rilevato",

	"Display Missing Health": "Mostra Salute Mancante",
	"Font Size Multiplier": "Moltiplicatore Dimensione Font",
	"Allow Text Wrap": "Permetti Testo a Capo",
	"Move Token Name Onto Token": "Sposta Nome sul Token",
	"NPC HP Roll Mode": "Modalità Tiro PF PNG",
	"Animation Speed": "Velocità Animazione",

	"Add Source to Names": "Aggiungi Fonte ai Nomi",
	"Disable 5etools Links": "Disabilita Link 5etools",
	"Render Dice as Plain Text": "Mostra Dadi Come Testo",
	"Use Enrichers": "Usa Arricchitori",
	"Duplicate Handling Mode": "Modalità Gestione Duplicati",
	"Prefer Metric Distance/Speed (Where Available)": "Preferisci Distanza/Velocità Metriche",
	"Prefer Metric Weight (Where Available)": "Preferisci Peso Metrico",
	"Show Variants/Versions": "Mostra Varianti/Vers.",
	"Save Imported Images to Server": "Salva Immagini su Server",
	"Image/Token Directory": "Directory Immagini/Token",
	"Auto-Switch Sidebar Tabs": "Cambia Automaticamente Schede",

	// Source filter
	"Select All Standard Sources": "Seleziona Fonti Standard",
	"Select All Partnered Sources": "Seleziona Fonti Partner",
	"Select All Non-Standard Sources": "Seleziona Fonti Non Standard",
	"Select All Prerelease Sources": "Seleziona Fonti Prerelease",
	"Select All Homebrew Sources": "Seleziona Fonti Homebrew",
	"Select 2014 Sources": "Seleziona Fonti 2014",
	"Select 2024 Sources": "Seleziona Fonti 2024",
	"Select \"Vanilla\" Sources": "Seleziona Fonti \"Vanilla\"",
	"Select All Non-UA Sources": "Seleziona Fonti Non UA",
	"Select SRD Sources": "Seleziona Fonti SRD",
	"Select Basic Rules Sources": "Seleziona Fonti Regole Base",

	// Template buttons
	"Prune Empty Folders": "Pulisci Cartelle Vuote",
	"Configure Editor": "Configura Editor",
	"Select Target Directory": "Seleziona Directory Destinazione",
	"Filter Players": "Filtra Giocatori",
	"Set Ownership": "Imposta Proprietà",
	"Import as Module": "Importa come Modulo",
	"Import as World": "Importa come Mondo",
	"Spellcasting Method": "Metodo di Incantamento",
	"Preparation": "Preparazione",
	"Rename To:": "Rinomina In:",
	"Rename To (Short):": "Rinomina In (Breve):",
	"(Use full name)": "(Usa nome completo)",
	"Named Creature:": "Creatura Nominata:",
	"Scale CR To:": "Ridimensiona GS A:",
	"Summon Spell Level:": "Liv. Incant. Evocazione:",
	"Variant:": "Variante:",
	"Player Character:": "Personaggio Giocante:",
	"Default": "Predefinito",
	"Custom": "Personalizzato",
	"All Players": "Tutti i Giocatori",
	"Select by Date": "Seleziona per Data",
	"Include References": "Includi Riferimenti",
	"Include Variants": "Includi Varianti",
	"Export Selection": "Esporta Selezione",
	"Import Selection": "Importa Selezione",
	"Open Config Editor": "Apri Editor Config.",
	"Reset All": "Reimposta Tutto",
	"First Letter of Name": "Prima Lettera del Nome",
	"Toggle Configuration": "Attiva/Disattiva Config.",
	"Show Source Data": "Mostra Dati Fonte",
	"Import as Journal Entries": "Importa come Note",
	"Use Compendium Browser": "Usa Browser Compendio",
	"Embedded URL": "URL Incorporato",
	"Select 2014 Rules": "Seleziona Regole 2014",
	"Select 2024 Rules": "Seleziona Regole 2024",

	// Altre impostazioni comuni
	"Ability": "Caratteristica",
	"Ability Check Bonus": "Bonus Prova Caratteristica",
	"Alignment": "Allineamento",
	"Attack": "Attacco",
	"Armor Training": "Addestramento Armatura",
	"Hit Points": "Punti Ferita",
	"Speed": "Velocità",
	"Senses": "Sensi",
	"Skills": "Abilità",
	"Damage": "Danno",
	"Resistances": "Resistenze",
	"Immunities": "Immunità",
	"Languages": "Lingue",
	"Proficiencies": "Competenze",
	"Equipment": "Equipaggiamento",
	"Spellcasting": "Incantamento",
	"Spells Known": "Incantesimi Conosciuti",
	"Spell Slots": "Slot Incantesimo",
	"Prepared Spells": "Incantesimi Preparati",
	"At-Will": "A Volontà",
	"At will:": "A volontà:",
	"Always Prepared": "Sempre Preparato",
	"Always": "Sempre",
	"(None)": "(Nessuno)",
	"(Unknown)": "(Sconosciuto)",
	"Alignment": "Allineamento",
	"Active Elements": "Elementi Attivi",
	"Action Stations": "Stazioni d'Azione",
	"Additional Homebrew Files": "File Homebrew Aggiuntivi",
	"Additional Prerelease Files": "File Prerelease Aggiuntivi",
	"Alternate Names": "Nomi Alternativi",
	"Duplicate": "Duplica",
	"Export": "Esporta",
	"Import": "Importa",
	"Open": "Apri",
	"Close": "Chiudi",
	"Lock": "Blocca",
	"Unlock": "Sblocca",
	"Merge": "Unisci",
	"Split": "Dividi",
	"Expand All": "Espandi Tutto",
	"Collapse All": "Comprimi Tutto",
	"Show All": "Mostra Tutto",
	"Hide All": "Nascondi Tutto",
	"Preview": "Anteprima",
	"Open Sheet": "Apri Scheda",
	"Toggle": "Attiva/Disattiva",
	"Enable": "Abilita",
	"Disable": "Disabilita",
	"Allow Duplicates": "Permetti Duplicati",
	"Alignment": "Allineamento",
	"3D Model": "Modello 3D",
	"Size": "Dimensione",
	"Dimensions": "Dimensioni",
	"Weight": "Peso",
	"Value": "Valore",
	"Rarity": "Rarità",
	"Quantity": "Quantità",
	"Duration": "Durata",
	"Range": "Gittata",
	"Area": "Area",
	"Target": "Bersaglio",
	"Components": "Componenti",
	"Materials": "Materiali",
	"Ritual": "Rituale",
	"Concentration": "Concentrazione",
	"Casting Time": "Tempo di Lancio",
	"School": "Scuola",
	"Save": "Tiro Salvezza",
	"Effect": "Effetto",
	"Condition": "Condizione",
	"Undo": "Annulla",
	"Redo": "Ripristina",
	"Copy": "Copia",
	"Paste": "Incolla",
	"Cut": "Taglia",
	"Zoom In": "Ingrandisci",
	"Zoom Out": "Rimpicciolisci",
	"Full Screen": "Schermo Intero",
	"Exit Full Screen": "Esci Schermo Intero",
	"Print": "Stampa",
	"Refresh": "Aggiorna",
	"Submit": "Invia",
	"Back": "Indietro",
	"Next": "Avanti",
	"Previous": "Precedente",
	"Finish": "Fine",
	"Start": "Inizio",
	"Stop": "Ferma",
	"Pause": "Pausa",
	"Resume": "Riprendi",
	"Skip": "Salta",
	"Retry": "Riprova",
	"Try Again": "Riprova",
	"Learn More": "Scopri di Più",
	"Read More": "Leggi di Più",
	"Show More": "Mostra di Più",
	"Show Less": "Mostra di Meno",
	"Manual": "Manuale",
	"Automatic": "Automatico",
	"Random": "Casuale",
	"Recharge": "Ricarica",
	"Charges": "Cariche",
	"Uses": "Usi",
	"Multiattack": "Multiattacco",
	"Legendary Actions": "Azioni Leggendarie",
	"Lair Actions": "Azioni di Tana",
	"Mythic Actions": "Azioni Mitiche",
	"Regional Effects": "Effetti Regionali",

	// === CONFIG SETTINGS ===
	"Ability Score Adjustment:": "Modifica Punteggi Caratteristica:",
	"Ability Score Increase.": "Incremento Punteggi Caratteristica.",
	"Ability Scores:": "Punteggi Caratteristica:",
	"Activate Scenes on Creation": "Attiva Scene alla Creazione",
	"Actor Spell Preparation": "Preparazione Incantesimi Attore",
	"Actor Spell Spellcasting Method": "Metodo Incantamento Attore",
	"Actors (Magic)": "Attori (Magici)",
	"Actors (Mundane)": "Attori (Comuni)",
	"Add Button To": "Aggiungi Bottone a",
	"Add Class to Creatures Imported as Player Characters": "Aggiungi Classe a Creature Importate come PG",
	"Add Scenes to Navigation": "Aggiungi Scene alla Navigazione",
	"Add Tag Suffixes to Names": "Aggiungi Suffissi Tag ai Nomi",
	"Add Unarmed Strike": "Aggiungi Attacco Senza Armi",
	"Add [CR] tag": "Aggiungi tag [GS]",
	"Add [type (with tags)] tag": "Aggiungi tag [tipo (con tag)]",
	"Add [type] tag": "Aggiungi tag [tipo]",
	"Additional Data Compendiums": "Compendi Dati Aggiuntivi",
	"Additional Data Compendiums (Backgrounds)": "Compendi Dati Aggiuntivi (Background)",
	"Additional Data Compendiums (Classes)": "Compendi Dati Aggiuntivi (Classi)",
	"Additional Data Compendiums (Features)": "Compendi Dati Aggiuntivi (Feature)",
	"Additional Data Compendiums (Subclasses)": "Compendi Dati Aggiuntivi (Sottoclassi)",
	"Adventure Rewards by CR ('24)": "Ricompense Avventura per GS ('24)",
	"Allow Actor Overwrite Imports": "Permetti Sovrascrittura Import Attori",
	"Allow Importer to Set 3D Models": "Permetti all'Importatore di Impostare Modelli 3D",
	"Allow importer to set": "Permetti all'importatore di impostare",
	"Alt Ability Scores by Class": "Punteggi Caratt. Alternativi per Classe",
	"Apply Class Filter when Opening on Actor": "Applica Filtro Classe all'Apertura su Attore",
	"Apply Level Filter when Opening on Actor": "Applica Filtro Livello all'Apertura su Attore",
	"Are You Sure?": "Sei Sicuro?",
	"As a Mythic Encounter": "Come Incontro Mitico",
	"Auto-Detect Actor Spellcasting Method": "Rilevamento Automatico Metodo Incantamento Attore",
	"Auto-Expand Page Embeds": "Espandi Automaticamente Pagine Incorporate",
	"Auto-Roll Multiattack Names": "Tiro Automatico Nomi Multiattacco",
	"Auto-Roll Multiattacks": "Tiro Automatico Multiattacchi",
	"Auto-Selected Source Count Warning Threshold": "Soglia Avviso Conteggio Fonti Auto-Selezionate",
	"Automatically Add Extra Fonts": "Aggiungi Automaticamente Font Aggiuntivi",
	"Automatically Update Blocklist from Rules Version": "Aggiorna Automaticamente Blocco dalla Versione Regole",
	"Avoid Loading Local Data": "Evita Caricamento Dati Locali",
	"Avoid Loading Prerelease/Homebrew Indexes on Startup": "Evita Caricamento Indici Prerelease/Homebrew all'Avvio",
	"Background Wave": "Onda Background",
	"Base Homebrew Repository URL": "URL Repository Homebrew Base",
	"Base Prerelease Repository URL": "URL Repository Prerelease Base",
	"Base Scene Repository URL": "URL Repository Scene Base",
	"Base Site URL": "URL del Sito Base",
	"Base items": "Oggetti Base",
	"Bonus Actions": "Azioni Bonus",
	"Browser Default": "Default del Browser",
	"Cards": "Carte",
	"Category": "Categoria",
	"Center": "Centro",
	"Class": "Classe",
	"Class Starting Gold": "Oro Iniziale di Classe",
	"Class/Subclass Default Image Fallback": "Immagine Fallback Default Classe/Sottoclasse",
	"Clear Rivet Target": "Cancella Target Rivet",
	"Close (CTRL to Close All)": "Chiudi (CTRL per Chiudere Tutti)",
	"Concentration Saving Throw Bonus": "Bonus Tiro Salvezza Concentrazione",
	"Condition (Reference)": "Condizione (Riferimento)",
	"Condition Immunity": "Immunità alle Condizioni",
	"Config": "Configurazione",
	"Constant Elements": "Elementi Costanti",
	"Control": "Controllo",
	"Convert Item Volumes to Metric": "Converti Volumi Oggetti in Metrici",
	"Convert Item Weights to Metric": "Converti Pesi Oggetti in Metrici",
	"Convert Ranges and Areas to Metric": "Converti Gittate e Aree in Metrici",
	"Convert Ranges to Metric": "Converti Gittate in Metrici",
	"Convert Scene Grid Distances to Metric": "Converti Distanze Griglia Scena in Metrici",
	"Convert Speeds to Metric": "Converti Velocità in Metrici",
	"Convert Token Vision Ranges to Metric": "Converti Gittate Visione Token in Metrici",
	"Copied Manifest URL!": "URL Manifest Copiato!",
	"Copy ID": "Copia ID",
	"Cost": "Costo",
	"Countermeasures": "Contromisure",
	"Create Backing Compendium?": "Creare Compendio di Supporto?",
	"Creature Type:": "Tipo Creatura:",
	"Currency": "Valuta",
	"Custom (see below)": "Personalizzato (vedi sotto)",
	"Custom Backend Endpoint": "Endpoint Backend Personalizzato",
	"Custom URL": "URL Personalizzato",
	"Customize and Import...": "Personalizza e Importa...",
	"Customize and Select...": "Personalizza e Seleziona...",
	"Damage Immunity": "Immunità ai Danni",
	"Damage Resistance": "Resistenza ai Danni",
	"Damage Resistances": "Resistenze ai Danni",
	"Damage Vulnerability": "Vulnerabilità ai Danni",
	"Debug Color Scheme": "Schema Colori Debug",
	"Debug Document Operations": "Operazioni Documento Debug",
	"Debug Hooks": "Hook Debug",
	"Debug Image Fetching": "Recupero Immagini Debug",
	"Debug Innate Scaling Delta": "Delta Scalatura Innata Debug",
	"Debug Side-Loaded Matches": "Corrispondenze Caricamento Laterale Debug",
	"Debug Unused Activity Damage Blocks": "Blocchi Danno Attività Inutilizzati Debug",
	"Deduplicate Nested Feature Selection": "Deduplica Selezione Feature Annidate",
	"Default (Sane Magic Item Prices homebrew)": "Default (Prezzi Oggetti Magici Sani homebrew)",
	"Default Deck": "Mazzo Default",
	"Default Ownership": "Proprietà Default",
	"Default Weapon Target": "Bersaglio Arma Default",
	"Delete All": "Elimina Tutto",
	"Delete Temp Folder?": "Eliminare Cartella Temp?",
	"Description": "Descrizione",
	"Detection:": "Rilevamento:",
	"Dice (Damage)": "Dadi (Danno)",
	"Directory/Compendium (Magic)": "Directory/Compendio (Magici)",
	"Directory/Compendium (Mundane)": "Directory/Compendio (Comuni)",
	"Disable Actor Overwrite Warning": "Disabilita Avviso Sovrascrittura Attore",
	"Disable Large Import Warning": "Disabilita Avviso Import Grandi",
	"Display Extension Detected": "Estensione Display Rilevata",
	"Display Scene Sheets on Creation": "Mostra Schede Scena alla Creazione",
	"Display Sources": "Mostra Fonti",
	"Dogma": "Dogma",
	"Domains": "Domini",
	"Downtime Activity: Scribing a Spell Scroll (XGE)": "Attività Tempo Libero: Scriba Pergamena (XGE)",
	"Drag-Drop Images As": "Trascina e Rilascia Immagini Come",
	"Drag-Drop Position Anchor": "Ancoraggio Posizione Trascinamento",
	"Dragon Hoard": "Tesoro del Drago",
	"Dragons as Innate Spellcasters": "Draghi come Incantatori Innati",
	"Dragons as Innate Spellcasters (FTD)": "Draghi come Incantatori Innati (FTD)",
	"Dragons as Innate Spellcasters (MM)": "Draghi come Incantatori Innati (MM)",
	"Draw Post-Transform Debug Regions": "Disegna Regioni Debug Post-Trasformazione",
	"Draw Pre-Transform Debug Regions": "Disegna Regioni Debug Pre-Trasformazione",
	"Duration:": "Durata:",
	"Dynamic Elements": "Elementi Dinamici",
	"Dynamic Ring Background Color": "Colore Sfondo Anello Dinamico",
	"Dynamic Ring Color": "Colore Anello Dinamico",
	"Dynamic Ring Effects": "Effetti Anello Dinamico",
	"Enable Data Source Filtering for GMs": "Abilita Filtro Fonti Dati per GM",
	"Enable Data Source Filtering for Players": "Abilita Filtro Fonti Dati per Giocatori",
	"Enable Legacy Package Importer": "Abilita Importatore Pacchetti Legacy",
	"Enable Token Dynamic Rings": "Abilita Anelli Dinamici Token",
	"Enable Token Vision": "Abilita Visione Token",
	"Enabled, and Unlock Slots": "Abilitato e Sblocca Slot",
	"Enabled, but Unlock Slots": "Abilitato ma Sblocca Slot",
	"Enhance Active Effect Config UI": "Migliora Interfaccia Config Effetti Attivi",
	"Equipment Shop": "Negozio Equipaggiamento",
	"Exclude": "Escludi",
	"Exclude UA/etc. Content": "Escludi Contenuti UA/ecc.",
	"Exotic Languages": "Lingue Esotiche",
	"Expertise": "Perizia",
	"Favored Weapons": "Armi Preferite",
	"Features": "Feature",
	"Fetch Supplementary Data from Scene Repository": "Recupera Dati Supplementari dal Repository Scene",
	"Filter Compatability Warnings": "Filtra Avvisi Compatibilità",
	"Firearms": "Armi da Fuoco",
	"Fix ESC Key": "Correggi Tasto ESC",
	"Fix Freehand Drawing Minimum Distance": "Correggi Distanza Minima Disegno Mano Libera",
	"Force Select All for GMs": "Forza Selezione Tutti per GM",
	"Force Select All for Players": "Forza Selezione Tutti per Giocatori",
	"Foundry Assets": "Asset Foundry",
	"Friendly": "Amichevole",
	"Gargantuan or larger": "Gigantesco o maggiore",
	"Gems/Art Objects": "Gemme/Oggetti d'Arte",
	"Generate Scene Thumbnails": "Genera Miniature Scene",
	"Goals:": "Obiettivi:",
	"Grapple": "Lotta",
	"Grappled": "Lottato",
	"Half proficiency": "Mezza competenza",
	"Haunt Bonus:": "Bonus Presenza:",
	"Health Attribute": "Attributo Salute",
	"Hidden Categories": "Categorie Nascoste",
	"Hidden Importers": "Importatori Nascosti",
	"Hide GM-Only Config": "Nascondi Config Solo GM",
	"Hide Missing Health on Defeated Tokens": "Nascondi Salute Mancante su Token Sconfitti",
	"Hide Subclasses in Class Importer": "Nascondi Sottoclassi nell'Importatore Classi",
	"High Elf": "Alto Elfo",
	"Highest spell count": "Conteggio incantesimi più alto",
	"Hill Dwarf": "Nano delle Colline",
	"Hit Points Increase Custom Roll Formula": "Formula Personalizzata Aumento PF",
	"Hit Points Increase Mode": "Modalità Aumento PF",
	"Home Plane": "Piano Natale",
	"Homebrew": "Homebrew",
	"Homebrew Modifications": "Modifiche Homebrew",
	"Hostile": "Ostile",
	"Hover": "Sopra",
	"Identify when Importing": "Identifica durante l'Importazione",
	"Ignore Types When Deduplicating": "Ignora Tipi in Deduplicazione",
	"Image Preloader Limit": "Limite Precaricamento Immagini",
	"Image Saving Mode": "Modalità Salvataggio Immagini",
	"Import All": "Importa Tutto",
	"Import Class Table to Description": "Importa Tabella Classe nella Descrizione",
	"Import Class?": "Importare Classe?",
	"Import Currency as Sheet Item for NPCs": "Importa Valuta come Oggetto Scheda per PNG",
	"Import Features to Description": "Importa Feature nella Descrizione",
	"Import Fluff Images to Description": "Importa Immagini Fluff nella Descrizione",
	"Import Fluff Text to Description": "Importa Testo Fluff nella Descrizione",
	"Import Fluff to Biography": "Importa Fluff nella Biografia",
	"Import Fluff to Description": "Importa Fluff nella Descrizione",
	"Import Item Stacks to Actors as Constituent Items": "Importa Pile Oggetti come Oggetti Costituenti",
	"Import Lower Levels?": "Importare Livelli Inferiori?",
	"Import Packs to Actors as Constituent Items": "Importa Pacchetti come Oggetti Costituenti",
	"Import Text as Description": "Importa Testo come Descrizione",
	"Import Variants as Features": "Importa Varianti come Feature",
	"Import as Spells": "Importa come Incantesimi",
	"Include": "Includi",
	"Include Caster Classes in Spell Description": "Includi Classi Incantatrici nella Descrizione",
	"Include Damage, Properties, Rarity, and Attunement in Description": "Includi Danni, Proprietà, Rarità e Sintonia",
	"Include Fluff Image in Biography": "Includi Immagine Fluff in Biografia",
	"Include Fluff Image in Description": "Includi Immagine Fluff in Descrizione",
	"Include Mastery Text in Description": "Includi Testo Maestria in Descrizione",
	"Include Property Text in Description": "Includi Testo Proprietà in Descrizione",
	"Include Variants in Biography": "Includi Varianti in Biografia",
	"Initiative": "Iniziativa",
	"Innate Spellcasting": "Incantatore Innato",
	"Integrations (3D Canvas)": "Integrazioni (Tela 3D)",
	"Integrations (Babele)": "Integrazioni (Babele)",
	"Integrations (Foundry Summons)": "Integrazioni (Evocazioni Foundry)",
	"Integrations (Quick Insert)": "Integrazioni (Inserimento Rapido)",
	"Integrations (Spotlight Omnisearch)": "Integrazioni (Ricerca Universale Spotlight)",
	"Inventory Stacking Mode": "Modalità Impilamento Inventario",
	"Item Weight & Value Scaling": "Scalatura Peso e Valore Oggetti",
	"Journal Entries": "Note del Diario",
	"Journal notes": "Note diario",
	"Large": "Grande",
	"Left-Align Scene Names": "Allinea a Sinistra Nomi Scene",
	"Legacy Content (&apos;14)": "Contenuti Legacy ('14)",
	"Light": "Luce",
	"Lightfoot Halfling": "Halfling Piedelesto",
	"Load Local Homebrew": "Carica Homebrew Locale",
	"Load Local Prerelease Content": "Carica Contenuti Prerelease Locali",
	"Local Homebrew Directory": "Directory Homebrew Locale",
	"Local Prerelease Content Directory": "Directory Contenuti Prerelease Locali",
	"Loot Tables": "Tabelle Bottino",
	"MSE: Add Audio as Sound Effect": "MSE: Aggiungi Audio come Effetto Sonoro",
	"Maintain Images when Overwriting Duplicates": "Mantieni Immagini in Sovrascrittura Duplicati",
	"Map URL/Path List": "Elenco URL/Percorsi Mappe",
	"Martial Weapons": "Armi Marziali",
	"Max Prepared Spells": "Max Incantesimi Preparati",
	"Medium or smaller": "Media o inferiore",
	"Minimum Permission Level": "Livello Permesso Minimo",
	"Minimum Permission Level For Over-Spending": "Livello Permesso Minimo per Spesa Eccessiva",
	"Minimum Permission Level for Bulk Directory Mover": "Livello Permesso Minimo per Sposta Directory",
	"Minimum Permission Level for Bulk Ownership Editor": "Livello Permesso Minimo per Editor Proprietà",
	"Minimum Permission Level for Bulk Prototype Token Editor": "Livello Permesso Minimo per Editor Token Prototipo",
	"Minimum Permission Level for Compendium Ownership Updater": "Livello Permesso Minimo per Agg. Proprietà Compendio",
	"Minimum Permission Level for Content Updater": "Livello Permesso Minimo per Agg. Contenuti",
	"Minimum Permission Level for Directory Buttons": "Livello Permesso Minimo per Bottoni Directory",
	"Minimum Permission Level for Directory Cleaner": "Livello Permesso Minimo per Pulizia Directory",
	"Minimum Permission Level for Directory Deduplicator": "Livello Permesso Minimo per Dedup Directory",
	"Minimum Permission Level for Import": "Livello Permesso Minimo per Import",
	"Minimum Permission Level for Importer Image Preloader": "Livello Permesso Minimo per Precaricamento Immagini",
	"Minimum Permission Level for Loot Generator": "Livello Permesso Minimo per Gen. Bottino",
	"Minimum Permission Level for Other Actor Tools": "Livello Permesso Minimo per Altri Strumenti Attore",
	"Minimum Permission Level for Other Table Tools": "Livello Permesso Minimo per Altri Strumenti Tabella",
	"Minimum Permission Level for Package Importer": "Livello Permesso Minimo per Import. Pacchetti",
	"Minimum Permission Level for Polymorph Tool": "Livello Permesso Minimo per Strumento Polimorfismo",
	"Minimum Permission Level for World Content Blocklist": "Livello Permesso Minimo per Blocco Contenuti Mondo",
	"Minimum Permission Level for World Data Source Selector": "Livello Permesso Minimo per Selettore Fonti Mondo",
	"Miscellaneous": "Varie",
	"Modern Content (&apos;24)": "Contenuti Moderni ('24)",
	"NPC HP Roll Mode (Summons)": "Modalità Tiro PF PNG (Evocazioni)",
	"Neutral": "Neutrale",
	"No Price": "Nessun Prezzo",
	"No proficiency": "Nessuna competenza",
	"No scaling": "Nessuna scalatura",
	"Not Prepared": "Non Preparato",
	"Note scene controls": "Controlli scena note",
	"Open Art Browser": "Apri Browser Arte",
	"Open Config": "Apri Configurazione",
	"Open Equipment Shop Targeting Current Sheet": "Apri Negozio per Scheda Corrente",
	"Open Equipment Shop Targeting Player Character": "Apri Negozio per Personaggio Giocante",
	"Open Import Wizard": "Apri Procedura Guidata Import",
	"Open Import Wizard Targeting Current Sheet": "Apri Import per Scheda Corrente",
	"Open Import Wizard Targeting Player Character": "Apri Import per Personaggio Giocante",
	"Open Loot Generator": "Apri Generatore Bottino",
	"Open Polymorpher Targeting Current Sheet": "Apri Polimorfismo per Scheda Corrente",
	"Open Polymorpher Targeting Player Character": "Apri Polimorfismo per Personaggio Giocante",
	"Opening...": "Apertura...",
	"Options": "Opzioni",
	"Order": "Ordine",
	"Other AC Bonus": "Altro Bonus CA",
	"Owner": "Proprietario",
	"Owner Hover": "Proprietario Sopra",
	"Ownership Updater": "Agg. Proprietà",
	"Package Index URL": "URL Indice Pacchetti",
	"Pact Magic": "Magia del Patto",
	"Pantheon": "Pantheon",
	"Party Loot": "Bottino del Gruppo",
	"Playing Cards": "Carte da Gioco",
	"Plutonium Import": "Importa Plutonio",
	"Polymorpher": "Polimorfismo",
	"Populate Active Effects": "Popola Effetti Attivi",
	"Populate Summons Profiles": "Popola Profili Evocazione",
	"Prefer Flat Saving Throws": "Preferisci Tiri Salvezza Piatti",
	"Prefer Foundry/System Images": "Preferisci Immagini Foundry/Sistema",
	"Prefer Foundry/System Tokens": "Preferisci Token Foundry/Sistema",
	"Prefer Metric Volume (Where Available)": "Preferisci Volume Metrico (Dove Disponibile)",
	"Prepared": "Preparato",
	"Prepared Spell Mass-Toggler": "Att./Disatt. Incantesimi Preparati",
	"Prepend Active Scene Name to Browser Tab Name": "Anteponi Nome Scena Attiva alla Scheda",
	"Prerequisite": "Prerequisito",
	"Price Multiplier": "Moltiplicatore Prezzo",
	"Proficiency": "Competenza",
	"Proficiency Bonus... Bonus?": "Bonus Competenza... Bonus?",
	"Prone": "Prono",
	"Province": "Provincia",
	"Psi Points Custom/Legacy Resource": "Risorsa Personalizzata/Legacy Punti Psionici",
	"Psi Points Resource": "Risorsa Punti Psionici",
	"Random Treasure by CR ('14)": "Tesoro Casuale per GS ('14)",
	"Rare Languages": "Lingue Rare",
	"Reactions": "Reazioni",
	"Replacement Data Compendiums": "Compendi Dati di Sostituzione",
	"Report Bug": "Segnala Bug",
	"Ring Gradient": "Gradiente Anello",
	"Ring Pulse": "Impulso Anello",
	"Ritual Only": "Solo Rituale",
	"Rivet": "Rivet",
	"Rock Gnome": "Gnomo delle Rocce",
	"Roll Items Linked by @UUID[Actor.Item.] on Click": "Tira Oggetti Collegati da @UUID al Click",
	"Rule (Reference)": "Regola (Riferimento)",
	"Rules Version": "Versione Regole",
	"Save DC (Save)": "CD Tiro Salvezza",
	"Save Imported Images to Server (GitHub)": "Salva Immagini Importate su Server (GitHub)",
	"Save Imported Tokens to Server": "Salva Token Importati su Server",
	"Save Imported Tokens to Server (GitHub)": "Salva Token Importati su Server (GitHub)",
	"Saving Throw Bonus": "Bonus Tiro Salvezza",
	"Saving Throws": "Tiri Salvezza",
	"Scene Background Color (Dark)": "Colore Sfondo Scena (Scuro)",
	"Scene Background Color (Light)": "Colore Sfondo Scena (Chiaro)",
	"Scene Background Color Mode": "Modalità Colore Sfondo Scena",
	"Scene Fog Exploration": "Esplorazione Nebbia Scena",
	"Scene Padding": "Padding Scena",
	"Scene Token Vision": "Visione Token Scena",
	"Scene controls": "Controlli scena",
	"Scenes": "Scene",
	"School Default Image Fallback": "Immagine Fallback Default Scuola",
	"Script": "Script",
	"Secret": "Segreto",
	"Secret Languages": "Lingue Segrete",
	"Sense (Reference)": "Senso (Riferimento)",
	"Set Current Sheet as Rivet Target": "Imposta Scheda Corrente come Target Rivet",
	"Set Current Token as Rivet Target": "Imposta Token Corrente come Target Rivet",
	"Set Document Operations Canary Flags": "Imposta Flag Canary Operazioni Documento",
	"Set Minimum Actor XP on Class Import": "Imposta XP Minimo Attore su Import Classe",
	"Set Player Character as Rivet Target": "Imposta PG come Target Rivet",
	"Set Value From Rarity": "Imposta Valore dalla Rarità",
	"Set as Rivet Target": "Imposta come Target Rivet",
	"Shared Campaign Variant Rules (XGE)": "Regole Varianti Campagna Condivisa (XGE)",
	"Shove": "Spinta",
	"Show Folder Linked by @UUID[Folder.] on Click": "Mostra Cartella Collegata da @UUID al Click",
	"Show Parent Icon/Name For Child @UUIDs": "Mostra Icona/Nome Genitore per @UUID Figli",
	"Show Players": "Mostra Giocatori",
	"Signature Spells:": "Incantesimi Firma:",
	"Simple Weapons": "Armi Semplici",
	"Size:": "Dimensione:",
	"Skill (Reference)": "Abilità (Riferimento)",
	"Skip Addon: Automation Check": "Salva Controllo Addon: Automation",
	"Skip Backend Check": "Salta Controllo Backend",
	"Skip Compendium Image Fetch": "Salva Recupero Immagini Compendio",
	"Snapshot Decks": "Mazzi Istantanea",
	"Snapshots": "Istantanee",
	"Species": "Specie",
	"Speed:": "Velocità:",
	"Spell": "Incantesimo",
	"Spell Attack Bonus (Melee)": "Bonus Attacco Incantesimo (Mischia)",
	"Spell Attack Bonus (Ranged)": "Bonus Attacco Incantesimo (A Distanza)",
	"Spell Damage Bonus (Melee)": "Bonus Danno Incantesimo (Mischia)",
	"Spell Damage Bonus (Ranged)": "Bonus Danno Incantesimo (A Distanza)",
	"Spell Item Preparation": "Preparazione Oggetto Incantesimo",
	"Spell Item Spellcasting Method": "Metodo Incantamento Oggetto Incantesimo",
	"Spell Points": "Punti Incantesimo",
	"Spell Points Custom/Legacy Resource": "Risorsa Personalizzata/Legacy Punti Incantesimo",
	"Spell Points Resource": "Risorsa Punti Incantesimo",
	"Spell Save DC Bonus": "Bonus CD Tiro Salvezza Incantesimo",
	"Spell Scroll": "Pergamena",
	"Spell Scroll Custom Prices": "Prezzi Personalizzati Pergamene",
	"Spell Scroll Price Mode": "Modalità Prezzo Pergamene",
	"Spellcasting Primary Trait Selection Method": "Metodo Selezione Caratteristica Primaria Incantamento",
	"Spellwrought Tattoo": "Tatuaggio Incantato",
	"Standard Languages": "Lingue Standard",
	"Subclass": "Sottoclasse",
	"Subclass Default Image Fallback": "Immagine Fallback Default Sottoclasse",
	"Subtype": "Sottotipo",
	"Summons Folder Name": "Nome Cartella Evocazioni",
	"Support Variables in Active Effect Values": "Supporta Variabili nei Valori Effetti Attivi",
	"Suppress Advancements During Drop Flow": "Sopprimi Avanzamenti Durante Drop",
	"Switch to Layer on Drop": "Passa al Layer su Drop",
	"Symbol": "Simbolo",
	"Tab Name Suffix": "Suffisso Nome Scheda",
	"Target Document": "Documento Target",
	"Temp Folder Name": "Nome Cartella Temp",
	"Text Wrap Max Width Multiplier": "Moltiplicatore Larghezza Max Testo a Capo",
	"Text and Tags": "Testo e Tag",
	"Throwing Items": "Oggetti da Lancio",
	"Tile scene controls": "Controlli scena tile",
	"Tile/Scene Scaling": "Scalatura Tile/Scena",
	"Tiles": "Tile",
	"Time": "Tempo",
	"Time Between Multiattack Rolls (ms)": "Tempo tra Tiri Multiattacco (ms)",
	"Token": "Token",
	"Token Bar 1 Attribute": "Attributo Barra 1 Token",
	"Token Bar 2 Attribute": "Attributo Barra 2 Token",
	"Token Bar Display Mode": "Modalità Visualizzazione Barra Token",
	"Token Bright Light Radius": "Raggio Luce Intensa Token",
	"Token Detection Modes": "Modalità Rilevamento Token",
	"Token Dim Light Radius": "Raggio Luce Debole Token",
	"Token Disposition": "Disposizione Token",
	"Token Light Animation Intensity": "Intensità Animazione Luce Token",
	"Token Light Animation Speed": "Velocità Animazione Luce Token",
	"Token Light Animation Type": "Tipo Animazione Luce Token",
	"Token Light Color": "Colore Luce Token",
	"Token Light Emission Angle": "Angolo Emissione Luce Token",
	"Token Light Intensity": "Intensità Luce Token",
	"Token Lock Rotation": "Blocca Rotazione Token",
	"Token Name Display Mode": "Modalità Visualizzazione Nome Token",
	"Token Scale": "Scala Token",
	"Token Sight Angle": "Angolo Visione Token",
	"Token Size": "Dimensione Token",
	"Token Vision Mode": "Modalità Visione Token",
	"Token Vision Range": "Gittata Visione Token",
	"Token Vision Saturation": "Saturazione Visione Token",
	"Token scene controls": "Controlli scena token",
	"Tool Proficiencies": "Competenze Strumenti",
	"Tools": "Strumenti",
	"Top-Left Corner": "Angolo Superiore Sinistro",
	"Traits": "Tratti",
	"Treat Journal Entries as Folders": "Tratta Note Diario come Cartelle",
	"Trigger": "Innesco",
	"Trigger:": "Innesco:",
	"Typical Cultists:": "Cultisti Tipici:",
	"Typical Worshipers": "Fedeli Tipici",
	"Unarmed Strike": "Attacco Senza Armi",
	"Unarmored Defense": "Difesa Senza Armatura",
	"Unknown Background": "Background Sconosciuto",
	"Unknown Class": "Classe Sconosciuta",
	"Unknown Species": "Specie Sconosciuta",
	"Unknown Subclass": "Sottoclasse Sconosciuta",
	"Unnamed Action": "Azione Senza Nome",
	"Unwrap Long Compendium Names": "Dividi Nomi Lunghi Compendio",
	"Upload File": "Carica File",
	"Use Advancement-Backing Compendium": "Usa Compendio di Supporto Avanzamenti",
	"Use Baldur's Gate 3 Icons": "Usa Icone Baldur's Gate 3",
	"Use Custom Icons for SRD Spells": "Usa Icone Personalizzate per Incantesimi SRD",
	"Use Custom Natural Armor Formula": "Usa Formula Armatura Naturale Personalizzata",
	"Use Foundry default": "Usa default Foundry",
	"Use Importer when Drag-Dropping Items to Actors": "Usa Importatore quando Trascini Oggetti su Attori",
	"Use Local Images": "Usa Immagini Locali",
	"Use Modded Package Installer": "Usa Installatore Pacchetti Moddato",
	"Use Rarity Pricing": "Usa Prezzi per Rarità",
	"Use Spell Points": "Usa Punti Incantesimo",
	"Use Spell Points (NPCs)": "Usa Punti Incantesimo (PNG)",
	"Use Static AC Values": "Usa Valori CA Statici",
	"Use Strict Entity Matching": "Usa Corrispondenza Entità Rigorosa",
	"Use Token Image as Portrait": "Usa Immagine Token come Ritratto",
	"Use Translated Descriptions": "Usa Descrizioni Tradotte",
	"Use game setting": "Usa impostazione di gioco",
	"Use importer-specific setting": "Usa impostazione specifica importatore",
	"Use rules version": "Usa versione regole",
	"User Art Directory": "Directory Arte Utente",
	"Weapon Attack Rolls": "Tiri Attacco Arma",
	"Weapon Attack and Damage Rolls": "Tiri Attacco e Danno Arma",
	"Weapon Damage Rolls": "Tiri Danno Arma",
	"Weapon Proficiencies": "Competenze Armi",
	"World Data Source Selection": "Selezione Fonti Dati Mondo",
	"Wrap Long Folder Names": "Dividi Nomi Cartelle Lunghi",
	"ZIP (Warning: rate-limited)": "ZIP (Attenzione: limitato)",
};

class PlutoniumItaliano {
	static _MOD_DATA_URL_RE = /^https:\/\/5e\.tools\/data\//;
	static _timer = null;

	static init () {
		Hooks.on("ready", () => {
			if (!globalThis.DataUtil) return;

			PlutoniumItaliano._patchDataLoading();

			// Hook direttamente sul render dell'importatore
			Hooks.on("renderChooseImporter", () => PlutoniumItaliano._translate());
			Hooks.on("renderApplication", () => PlutoniumItaliano._delayedTranslate());
			Hooks.on("renderDialog", () => PlutoniumItaliano._delayedTranslate());
			Hooks.on("renderSettingsConfig", () => PlutoniumItaliano._delayedTranslate());

			// MutationObserver per UI dinamica
			const obs = new MutationObserver(() => PlutoniumItaliano._delayedTranslate());
			obs.observe(document.body, { childList: true, subtree: true });

			// Traduzione iniziale
			setTimeout(() => PlutoniumItaliano._translate(), 500);

			console.log(`${MODULE_ID} | Pronto`);
		});
	}

	static _delayedTranslate () {
		if (PlutoniumItaliano._timer) clearTimeout(PlutoniumItaliano._timer);
		PlutoniumItaliano._timer = setTimeout(PlutoniumItaliano._translate.bind(PlutoniumItaliano), 200);
	}

	static _patchDataLoading () {
		const _orig = DataUtil.loadJSON;
		DataUtil.loadJSON = function (url, ...args) {
			if (typeof url === "string" && PlutoniumItaliano._MOD_DATA_URL_RE.test(url))
				url = url.replace(PlutoniumItaliano._MOD_DATA_URL_RE, `${MODULE_PATH}/data/`);
			return _orig.call(this, url, ...args);
		};
		if (DataUtil.loadRawJSON) {
			const _origR = DataUtil.loadRawJSON;
			DataUtil.loadRawJSON = function (url, ...args) {
				if (typeof url === "string" && PlutoniumItaliano._MOD_DATA_URL_RE.test(url))
					url = url.replace(PlutoniumItaliano._MOD_DATA_URL_RE, `${MODULE_PATH}/data/`);
				return _origR.call(this, url, ...args);
			};
		}
	}

	static _translate () {
		// Traduce nodi di testo diretti in tutto il documento
		const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null, false);
		let node;
		while (node = walker.nextNode()) {
			const txt = node.textContent.trim();
			if (!txt || node._pltIta) continue;
			const tr = UI_TRANS[txt];
			if (tr) {
				node.textContent = tr;
				node._pltIta = true;
			}
		}

		// Traduce attributi title e placeholder di tutti gli elementi
		document.querySelectorAll("[title], [placeholder]").forEach(el => {
			if (el.title && UI_TRANS[el.title.trim()]) {
				const translated = UI_TRANS[el.title.trim()];
				if (el.title !== translated) el.title = translated;
			}
			if (el.placeholder && UI_TRANS[el.placeholder.trim()]) {
				const translated = UI_TRANS[el.placeholder.trim()];
				if (el.placeholder !== translated) el.placeholder = translated;
			}
		});
	}
}

Hooks.on("init", () => PlutoniumItaliano.init());
